### PR TITLE
Feature/context enabled parsing

### PR DESCRIPTION
**Pull request by PedroPareja**
This is an addition for the action mapping of the grammar so a custom context with arbitrary data can be provided when calling parse method and could be optionally used in a mapping action (when new Action interface is used). This way we can define previously and only once a grammar (Parser) and provided dynamic data which may be needed in the constructions at runtime (through the custom context).

This has been added to the 2.2.0 version because the project I am working on uses Java 8.

Example of use:

```
public class PowerExpressionProcessor
{
    @Autowired
    private FieldProcessor fieldProcessor;

    private Parser parser;

    public PowerExpressionProcessor()
    {
        Parser id = letter().seq(word().or(of('_')).star());
        Parser tableField = id.seq(of('.')).seq(id).flatten().map((String value, ParseContext parseContext) -> new DBExpField(fieldProcessor.getField(parseContext.getDataModel(), value)));

        Parser paramString = of('?').or((of('S').or(of('s')).seq(of('?')))).map(value -> new DBExpParam(FieldType.STRING));
        Parser paramInteger = of('I').or(of('i')).seq(of('?')).map(value -> new DBExpParam(FieldType.INT));
        Parser paramLong = of('L').or(of('l')).seq(of('?')).map(value -> new DBExpParam(FieldType.LONG));
        Parser paramBigDecimal = of('B').or(of('b')).seq(of('?')).map(value -> new DBExpParam(FieldType.BIGDECIMAL));
        Parser paramDate = of('D').or(of('d')).seq(of('?')).map(value -> new DBExpParam(FieldType.DATE));
        Parser paramTimestamp = of('T').or(of('t')).seq(of('?')).map(value -> new DBExpParam(FieldType.TIMESTAMP));

        Parser param = paramString.or(paramInteger).or(paramLong).or(paramBigDecimal).or(paramDate).or(paramTimestamp);

        parser = tableField.or(param);
    }

    public DBExpression parseExpression(DataModel dataModel, PowerExpression expression)
    {
        return parseExpression(dataModel, expression.getPowerExpression());
    }

    public DBExpression parseExpression(DataModel dataModel, String expression)
    {
        ParseContext parseContext = new ParseContext(dataModel);

        Result<ParseContext> result = parser.parse(expression, parseContext);

        if(result.isFailure())
            throw new ProcessorException(DataGatewayError.ERROR_EXP_PARSE_ERROR, "PowerExpression parse error at position " + result.getPosition() + ": " + result.getMessage());

        return result.get();
    }

    private static class ParseContext
    {
        private final DataModel dataModel;

        public ParseContext(DataModel dataModel)
        {
            this.dataModel = dataModel;
        }

        public DataModel getDataModel()
        {
            return dataModel;
        }
    }
} 
```

### CODE REVIEW

**Comment by renggli** [comment]
I am a bit worried: This makes the API more complicated, likely adds a notable performance cost to the central `Context` object, as well as probably breaks in fast-parse mode? I am wondering why you are not just instantiating `PowerExpressionProcessor` with your `ParseContext` as a field each time you run it?

**Comment by PedroPareja** [comment]
I don't understand why an extra pointer copy for the Context object would be a performance issue at all. In the other hand recreating the entire grammar each time a parsing is needed would add a big performance impact IMHO (if for example instantiate the class each time) as this is an small example of what is going to be a vast bigger grammar

**Comment by PedroPareja** [comment]
Anyway that is just an idea of how to solve the problem of the performance cost of having to replicate the grammar definition again and again when using dynamic data for the result constructions. I tried to write it so it fits in the best way and do not change anything in a meaningful way (that is why the custom context is inside the Context or the Action interface extends Java's function interface).

I just had to add this feature and I thought it would be nice to give back to the project.

**Comment by renggli** [comment]
It matters, because the pointer is added to an object that is instantiated and copied millions of times during a normal parse operation. Also it breaks an optimization added in later versions of the code that drops the creation of the `Context` object entirely to improve parse speed significantly. 

I do appreciate your contribution, however I think that forcing all users to pay for a slower experience for a feature that can be easily achieved in different ways is not something I want to add to the core library.

**Comment by PedroPareja** [comment]
Good to know. I really underestimated the number of times Context is copied in a parsing operation and it sounds terrible with or without that extra pointer (that in the case of not being used would be a null assignment; so understand my surprise when I am told that a null assignation in a constructor would make users to have a slower experience).

I think the API is brilliant but the way it is implemented is a no-go for us (performance wise). Also, recreating the grammar/rules structure for each parse is also a no-go (for the unnecessary performance penalty). Having all this in mind I will have to reimplement and redesign the internals to have the custom context and fix the general performance problem for the parsing in this version.

I appreciate your response as it frees me to no longer be aligned with the internals or the API signature in the further development that will take place as we will be taking a different path from here.

Thank you for your time and good luck.

**Pull request closed without merging**
